In [6]:
from plasma_classes import *
from plasma_utils import *
from matplotlib import pyplot as plt
from matplotlib import animation
from tqdm import tqdm

In [7]:
particles = Particles(10, 1.0, -1.0, 1.0)
particles.x = np.arange(10)
particles.v = np.arange(10)

In [8]:
def bar(particles):
    print(particles.n_macro)
    particles.x = 0

In [9]:
bar(particles[2:4])

2


In [10]:
particles.x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
def foo(particles):
    mask = particles.x < 4
    particles.delete(mask)

In [4]:
foo(particles)

In [5]:
particles.x

array([4, 5, 6, 7, 8, 9])

In [15]:
mask = particles.x < 4

In [16]:
mask

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [17]:
particles = particles[mask]

In [18]:
particles.x

array([0, 1, 2, 3])

In [2]:
import time

# Create 10 million particles
particles = Particles(10000000, 1.0, -1.0, 1.0)

# Modify individual particle velocities one at a time
start_time = time.time()
for i in range(5000000):
    particles.v[i] += 0.1
end_time = time.time()

print("Elapsed time: ", end_time - start_time, " seconds")

Elapsed time:  0.5579440593719482  seconds


In [3]:
slice1 = particles[3:5000000]

In [4]:
# Modify individual particle velocities one at a time
start_time = time.time()
for i in range(3000):
    slice1.v[i] += 1000
end_time = time.time()

print("Elapsed time: ", end_time - start_time, " seconds")

Elapsed time:  0.0  seconds


In [5]:
import numpy as np
import time

# Set up the particles array
n_particles = 100000
x = np.random.uniform(low=-1, high=1, size=n_particles)
v = np.random.normal(loc=0, scale=1, size=n_particles)
particles = Particles(n_particles, 1.0, 1.0, 1.0)
particles.x = x
particles.v = v

# Create a boolean mask
mask = np.random.choice([True, False], size=n_particles)

# Test the boolean index operation
t1 = time.time()
sub_particles = particles[mask]
t2 = time.time()
print(f"Boolean index operation took {t2-t1} seconds")

# Test the by-hand creation of new array with the same mask
t3 = time.time()
sub_particles = Particles(np.count_nonzero(mask), particles.concentration, particles.q, particles.m)
sub_particles.x = particles.x[mask]
sub_particles.v = particles.v[mask]
t4 = time.time()
print(f"By-hand creation of new array with the same mask took {t4-t3} seconds")


Boolean index operation took 0.0009968280792236328 seconds
By-hand creation of new array with the same mask took 0.0009965896606445312 seconds


In [6]:
# create original particles object
original_particles = Particles(10, 1.0, 1.0, 1.0)
original_particles.x = np.random.rand(10)

# make a deep copy of the original particles object
copy_particles = original_particles.deepcopy()

# modify the copy
copy_particles.x[0] = 0.0

# check that the original particles object is not modified
assert np.allclose(original_particles.x[0], 0.0) == False


In [7]:
original_particles.x

array([0.92823824, 0.76024596, 0.53362671, 0.0998817 , 0.07057969,
       0.72800722, 0.4734317 , 0.77427962, 0.16064182, 0.1847532 ])

In [8]:
sl = original_particles[2:7].deepcopy()
sl.x *= 10000
sl.x

array([5336.26709348,  998.8169768 ,  705.79688562, 7280.07222921,
       4734.31700472])

In [9]:
original_particles.x

array([0.92823824, 0.76024596, 0.53362671, 0.0998817 , 0.07057969,
       0.72800722, 0.4734317 , 0.77427962, 0.16064182, 0.1847532 ])

In [7]:
particles.v[3:]

array([2000.1, 2000.1, 2000.1, ...,    0. ,    0. ,    0. ])

In [42]:
slice6 = particles[3456 :5000000]

In [43]:
# Modify individual particle velocities one at a time
start_time = time.time()
for i in range(5000000):
    slice1.v[i] -= 2000
end_time = time.time()

print("Elapsed time: ", end_time - start_time, " seconds")

Elapsed time:  0.6053729057312012  seconds


In [44]:
particles.v

array([-999.9, -999.9, -999.9, ...,    0. ,    0. ,    0. ])

In [45]:
slc = particles[:20]

In [46]:
slc.x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [48]:
particles.x[:20] = []
slc.x

ValueError: could not broadcast input array from shape (0,) into shape (20,)

In [29]:
# Create a Particles object with 100 particles
particles = Particles(100, 1.0, -1.0, 1.0)

# Select a slice of the particles
sliced_particles = particles[10:30]

# Double the speed of the sliced particles
sliced_particles.v *= 2.0


# Verify that the parent Particles object was updated
assert np.allclose(particles.v[10:30], sliced_particles.v)


In [3]:
import numpy as np
import os

# Create instances of each class for testing
particles = Particles(100, 1.0, 1.0, 1.0)
particles.x = np.random.rand(100)
particles.v = np.random.rand(100)
nodes = Nodes(10)
nodes.rho = np.random.rand(11)
nodes.E = np.random.rand(11)
nodes.phi = np.random.rand(11)
wall = Wall(0, 1, 10, 0.1, 'left')
particle1 = Particles(10, 0.5, 1.5, 1.0)
particle1.x = np.random.rand(10)
particle1.v = np.random.rand(10)
particle2 = Particles(5, 0.5, 1.5, 1.0)
particle2.x = np.random.rand(5)
particle2.v = np.random.rand(5)
wall.particles_lst = [particle1, particle2]

# Test saving and loading of Particles objects
particles_path = 'particles.pkl'
save_to_file(particles, particles_path)
loaded_particles = load_from_file(particles_path)
assert isinstance(loaded_particles, Particles)
assert loaded_particles.n_macro == particles.n_macro
assert loaded_particles.concentration == particles.concentration
assert np.allclose(loaded_particles.x, particles.x)
assert np.allclose(loaded_particles.v, particles.v)

# Test saving and loading of Nodes objects
nodes_path = 'nodes.pkl'
save_to_file(nodes, nodes_path)
loaded_nodes = load_from_file(nodes_path)
assert isinstance(loaded_nodes, Nodes)
assert loaded_nodes.length == nodes.length
assert np.allclose(loaded_nodes.rho, nodes.rho)
assert np.allclose(loaded_nodes.E, nodes.E)
assert np.allclose(loaded_nodes.phi, nodes.phi)

# Test saving and loading of Wall objects
wall_path = 'wall.pkl'
save_to_file(wall, wall_path)
loaded_wall = load_from_file(wall_path)
assert isinstance(loaded_wall, Wall)
assert loaded_wall.left == wall.left
assert loaded_wall.right == wall.right
assert loaded_wall.number == wall.number
assert loaded_wall.h == wall.h
assert loaded_wall.side == wall.side
assert len(loaded_wall.particles_lst) == len(wall.particles_lst)
assert isinstance(loaded_wall.particles_lst[0], Particles)
assert loaded_wall.particles_lst[0].n_macro == particle1.n_macro
assert loaded_wall.particles_lst[0].concentration == particle1.concentration
assert loaded_wall.particles_lst[0].q == particle1.q
assert loaded_wall.particles_lst[0].m == particle1.m
assert np.allclose(loaded_wall.particles_lst[0].x, particle1.x)
assert np.allclose(loaded_wall.particles_lst[0].v, particle1.v)
assert isinstance(loaded_wall.particles_lst[1], Particles)
assert loaded_wall.particles_lst[1].n_macro == particle2.n_macro
assert loaded_wall.particles_lst[1].concentration == particle2.concentration
assert loaded_wall.particles_lst[1].q == particle2.q
assert loaded_wall.particles_lst[1].m == particle2.m
assert np.allclose(loaded_wall.particles_lst[1].x, particle2.x)
assert np.allclose(loaded_wall.particles_lst[1].v, particle2.v)

# Clean up the test files
os.remove(particles_path)
os.remove(nodes_path)
os.remove(wall_path)
